[theme]
base="#ff00cc"
backgroundColor="#90CAF9"
secondaryBackgroundColor="#0D47A1"
codeBackgroundColor="#ff0bd2"
textColor="#fbfbfb"

[theme.sidebar]
backgroundColor="#8BBB92"
secondaryBackgroundColor="#12544F"
textColor="#fbfbfb"